--CREATE DATABASE POLIZIA

CREATE TABLE AGENTE_DI_POLIZIA(
	ID_AGENTE_P INT IDENTITY (1,1) NOT NULL,
	CONSTRAINT PK_ID_AGENTE_P PRIMARY KEY (ID_AGENTE_P),
	NOME NVARCHAR(30),
	COGNOME NVARCHAR(50),
	CODICE_FISCALE NCHAR (16),-- MANCA UNIQUE 
	DATA_DI_NASCITA DATE, --(2021-Year(Datadinascita)>=18)
	ANNI_DI_SERVIZIO INT NOT NULL,
	
);




CREATE TABLE AREA_METROPOLITANA(
	ID_AREA_M INT IDENTITY(1,1) NOT NULL,
	CONSTRAINT PK_ID_AREA_M PRIMARY KEY(ID_AREA_M),
	CODICE_AREA NVARCHAR(5), -- NCHAR, UNIQUE
	ALTO_RISCHIO INT CHECK(ALTO_RISCHIO=0 OR ALTO_RISCHIO=1),
	
);


CREATE TABLE AGAM(
	ID_AGENTE_POLIZIA INT,
	ID_AREA_METRO INT,
	CONSTRAINT FK_AREA_METRO FOREIGN KEY (ID_AREA_METRO)
	REFERENCES AGENTE_DI_POLIZIA(ID_AGENTE_P),
	CONSTRAINT FK_AGENTE_POLIZIA FOREIGN KEY (ID_AGENTE_POLIZIA)
	REFERENCES AREA_METROPOLITANA(ID_AREA_M)
);


--INSERIMENTO DATI--
--POLIZIA--

INSERT INTO AGENTE_DI_POLIZIA VALUES('KEVIN','BLAKE','IT96P123LK96TR59','1994-02-21',6);
INSERT INTO AGENTE_DI_POLIZIA VALUES('ALICE','MOON','IT66P423LK97TR19','1995-08-11',4);
INSERT INTO AGENTE_DI_POLIZIA VALUES('ALEX','ROSSI','IT32P123LK96TR51','1991-11-03',8);
INSERT INTO AGENTE_DI_POLIZIA VALUES('ANNA','BIANCHI','IT23P121PO36TR51','1996-10-04',2);

SELECT * FROM AGENTE_DI_POLIZIA

--AREA METROPOLITANA--

INSERT INTO AREA_METROPOLITANA VALUES('12AB3',0);
INSERT INTO AREA_METROPOLITANA VALUES('13KP4',0);
INSERT INTO AREA_METROPOLITANA VALUES('08AR1',1);
INSERT INTO AREA_METROPOLITANA VALUES('00AV8',1);

SELECT * FROM AREA_METROPOLITANA

---AGAM--

INSERT INTO AGAM VALUES(1,1);
INSERT INTO AGAM VALUES(1,2);
INSERT INTO AGAM VALUES(2,3);
INSERT INTO AGAM VALUES(2,2);
INSERT INTO AGAM VALUES(3,1);
INSERT INTO AGAM VALUES(4,4);
INSERT INTO AGAM VALUES(4,1);

SELECT * FROM AGAM

----ESERCIZIO---

--VISUALIZZARE L'ELENCO DEGLI AGENTI CHE LAVORANO IN AREA AD ALTRO RISCHIO E HANNO MENO DI 3 ANNI DI SERVIZIO--

SELECT A.NOME,A.COGNOME,A.CODICE_FISCALE,A.DATA_DI_NASCITA,A.ANNI_DI_SERVIZIO
FROM AGENTE_DI_POLIZIA A 
JOIN AGAM G ON G.ID_AGENTE_POLIZIA=A.ID_AGENTE_P
JOIN AREA_METROPOLITANA M ON G.ID_AREA_METRO=M.ID_AREA_M
WHERE M.ALTO_RISCHIO=1 AND A.ANNI_DI_SERVIZIO<3


--VISUALIZZARE IL NUMERO DI AGENTI ASSEGNATI PER OGNI AREA GEOGRAFICA(NUMERO AGENTI E CODICE AREA)--

SELECT COUNT(A.ID_AGENTE_P) AS [NUMERO AGENTI],M.CODICE_AREA [CODICE AREA]
FROM AGENTE_DI_POLIZIA AS A
JOIN AGAM G ON G.ID_AGENTE_POLIZIA=A.ID_AGENTE_P
JOIN AREA_METROPOLITANA M ON M.ID_AREA_M=G.ID_AREA_METRO
GROUP BY M.CODICE_AREA
